name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:

    runs-on: ubuntu-latest

    container: ghcr.io/neatoro/osdev-container:main


    steps:

      - uses: actions/checkout@v2


      - name: Building
        run: ash scripts/build.sh


      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: buildos
          path: bin/buildos.bin
